[build]
  command = "npm run build"
  publish = "ai-humanizer-website/build"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm start"
  targetPort = 3000
  publish = "ai-humanizer-website/build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
