[build]
  base = "ai-humanizer-website"
  publish = "ai-humanizer-website/build"
  command = "npm install --legacy-peer-deps && npm run build"
  
[functions]
  directory = "netlify/functions"

[dev]
  command = "npm start"
  targetPort = 3000
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
